
services:
  mariadb:
    container_name: inception-mariadb
    build: ./requirements/mariadb
    restart: always
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin --user=$${DB_USER} --pass=$${DB_PASS} --host=localhost ping"]
      start_period: 10s
      interval: 5s
      timeout: 10s
      retries: 3
    networks:
      - inception-network
  wordpress:
    container_name: inception-wordpress
    build: ./requirements/wordpress
    restart: always
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "service php7.4-fpm status | grep running"]
      start_period: 10s
      interval: 5s
      timeout: 10s
      retries: 3
    networks:
      - inception-network
  nginx:
    container_name: inception-nginx
    build: ./requirements/nginx
    #restart: always
    env_file: # not sure if its used yet
      - .env
    ports:
      - "443:443"
    depends_on:
      wordpress:
        condition: service_healthy
    networks:
      - inception-network

volumes:
  mariadb:
    driver: local
    driver_opts:
      device: /home/$USERNAME/data/mariadb
      o: bind
      type: none
  wordpress:
    driver: local
    driver_opts:
      device: /home/$USERNAME/data/wordpress
      o: bind
      type: none

networks:
  inception-network:
    driver: bridge
