services:
  mariadb:
    container_name: inception-mariadb
    image: mariadb:42
    build: ./requirements/mariadb
    restart: always
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin --user=$${DB_USER} --pass=$${DB_PASS} --host=localhost ping"]
      start_period: 10s
      interval: 5s
      timeout: 10s
      retries: 3
    networks:
      - inception-network
  wordpress:
    container_name: inception-wordpress
    build: ./requirements/wordpress
    image: wordpress:42
    restart: always
    volumes:
      - wordpress:/var/www/html
    depends_on:
      mariadb:
        condition: service_healthy
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "service php7.4-fpm status | grep running"]
      start_period: 10s
      interval: 5s
      timeout: 10s
      retries: 3
    networks:
      - inception-network
  nginx:
    container_name: inception-nginx
    image: nginx:42
    build: ./requirements/nginx
    restart: always
    volumes:
      - wordpress:/var/www/html
    depends_on:
      wordpress:
        condition: service_healthy
    ports:
      - "443:443"
    networks:
      - inception-network

volumes:
  mariadb:
    driver: local
    driver_opts:
      device: ${USER_HOME}/data/mariadb
      o: bind
      type: none
  wordpress:
    driver: local
    driver_opts:
      device: ${USER_HOME}/data/wordpress
      o: bind
      type: none

networks:
  inception-network:
    driver: bridge
