
services:
  mariaDB:
    container_name: Inception-MariaDB
    build: ./requirements/mariaDB
    restart: always
    volumes:
      - mariadb:/var/lib/mysql
    env-file:
      - .env
    networks:
      - inception-network

volumes:
  mariadb:
    driver: local
    drivet_opts:
      device: /home/$USER/data/mariadb
      o: bind
      type: none

networks:
  inception-network:
    driver: bridge
