
services:
  mariadb:
    container_name: inception-mariadb
    build: ./requirements/mariaDB
    restart: always
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
    networks:
      - inception-network

volumes:
  mariadb:
    driver: local
    driver_opts:
      device: /home/$USERNAME/data/mariadb
      o: bind
      type: none

networks:
  inception-network:
    driver: bridge
